name: Test CodeCov
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  CodeCov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-umbrella # optional
        verbose: true # optional (default = false)
